### ISSUE TITLE
CUDA vs Naive Speedup?

### ISSUE THREAD

**Issue by glenn-jocher** [d-li14/involution#1]
@d-li14 hi, thanks for your contributions and for this amazing idea!

I'd like to try your involution() module in a non-mmdetection repo ([YOLOv5](https://github.com/ultralytics/yolov5)), and was trying to figure out the best technical way to do this using your existing code here:
- [det/mmdet/models/utils/involution_cuda.py](https://github.com/d-li14/involution/blob/main/det/mmdet/models/utils/involution_cuda.py)
- [det/mmdet/models/utils/involution_naive.py](https://github.com/d-li14/involution/blob/main/det/mmdet/models/utils/involution_naive.py)

The naive implementation seems easier to integrate into new works, so I'd like to use that, and my main question is:
How much of a speed change do you see in training (and inference) when moving from naive to cuda? Thanks!

**Comment by d-li14** [comment]
Thanks for your feedback!
We have not tried involution with the YOLO framework. Moreover, the practical change may depend on specific platforms and test settings. For reference, we consider another one-stage detector RetinaNet in our work. The inference speedup on a single NVIDIA V100 GPU is roughly 40%.
Another major drawback of the naive implementation is that it costs much GPU memory due to the harmful `unfold` operation.
