### ISSUE TITLE
How about replacing involution for convolution in BasicBlock?

### ISSUE THREAD

**Issue by beiliu253** [d-li14/involution#4]
Hi, 

great work! I have run simple experiments with RedNet on CIFAR10.  I notice that all RedNets in the paper use Bottleneck block for ResLayer. I've tried to replace the second 3x3 convolution in BasicBlock with involution to get RedNet18, RedNet34 from ResNet18, ResNet34 respectively . But the performance decreases according to my results. The accuracy of ResNet18 on CIFAR10 is 93.9%, while the RedNet18 is 92.1%.

I've noticed one sentence in the paper, which says "Indispensably, linear transformations (realized by 1×1 convolutions) are interspersed for channel information exchange". So, I am wondering if involution can succeed in BasicBlock for ResLayer. Or is 1×1 convolution an indispensable part for involution's success since there is no 1×1 convolution in BasicBlock of ResNet18?

Thank!

**Comment by d-li14** [comment]
(1) Note that involution uses fewer parameters/FLOPs than convolution. You may pay the price of performance for reduced model complexity. This is a trade-off between accuracy and efficiency to be played around.

(2) Because we seek long-range interactions on ImageNet, COCO, etc, which use a much larger input image size than CIFAR (32x32), involution kernel size is set to 7. For small datasets like CIFAR, this may not be the case.

(3) 1x1 convolution is not necessary for involution. For example, in the neck of detection models, we use involution individually without 1x1 convolution accompanied. The referred sentence means 1x1 convolution enhances channel information exchange, which is beneficial for the overall modeling ability of RedNet.

**Comment by beiliu253** [comment]
Got it! Thanks for your patient reply! Again, brilliant work!!!
